import { App, PluginSettingTab, Setting } from 'obsidian';
import Todoian from 'main';

export class TodoianSettingsTab extends PluginSettingTab {
    plugin: Todoian;

    constructor(app: App, plugin: Todoian) {
        super(app, plugin);
        this.plugin = plugin;
    }

    // für Darstellung der Settings
    display(): void {
        this.containerEl.empty();

        new Setting(this.containerEl)
            .setName('Todoist API Token')
            .setDesc('Enter your API Token generated by Todoist')
            .addText((text) => (
                // callback
                text
                    .setPlaceholder('Enter your Todoist API Token')
                    .setValue(this.plugin.settings.todoistApiToken)
                    .onChange(async (value) => {
                        this.plugin.settings.todoistApiToken = value;
                        await this.plugin.saveSettings();
                    })
            ));
        
        new Setting(this.containerEl)
            .setName('Filter Name')
            .setDesc('Enter the query for the tasks you want to display. When using the "Big 3 Tasks per day" Technique, I propose "p1 & today".')
            .addText((text) => (
                text
                    .setPlaceholder('p1 & today')
                    .setValue(this.plugin.settings.todoistFilter)
                    .onChange(async (value) => {
                        this.plugin.settings.todoistFilter = value;
                        await this.plugin.saveSettings();
                    })
            ));
    }
}